--!strict
-- Auto-generated by `tarmac sync --target roblox` (see tarmac.toml) — this
-- particular batch was instead uploaded manually via create.roblox.com and
-- hand-transcribed here (Liam's machine hit a Tarmac/Roblox CSRF-handshake
-- issue that manual upload sidesteps) — same `{ [path] = "rbxassetid://..." }`
-- shape either way, so nothing else needs to change once uploads succeed
-- normally. Still missing: tiles/grass.png, tiles/path.png,
-- tiles/sakura_grass.png, tiles/tilled_soil.png, tiles/water.png — add
-- those once uploaded (falls back to a blank placeholder until then).
-- Also missing: sprites/player_idle.png + sprites/player_walk.png (the
-- pack's character walk/idle sheets, now in assets/sprites/) — the 2D
-- sprite-character conversion (CharacterSpriteController.lua) stays
-- dormant, keeping normal 3D avatars, until BOTH are uploaded and
-- listed here; then it activates with no code change. And
-- sprites/fish_generic.png (any fish image works) for the reel-in's
-- placeholder fish standee (FishingRig.lua).
return {
	["sprites/player_placeholder.png"] = "rbxassetid://113485555309209",
	["sprites/petal.png"] = "rbxassetid://135838448433089",
	["sprites/kaya_placeholder.png"] = "rbxassetid://99746438596164",
	["sprites/tree_stump.png"] = "rbxassetid://72359641625412",
	["sprites/tree_small.png"] = "rbxassetid://103423679833698",
	["sprites/tree_large.png"] = "rbxassetid://108710081749902",
	["sprites/stone_round.png"] = "rbxassetid://112269019544306",
	["sprites/stone_cluster.png"] = "rbxassetid://139304812145738",
	["sprites/shrine_torii.png"] = "rbxassetid://83201818922646",
	["sprites/lantern.png"] = "rbxassetid://82367659629626",
	["sprites/house_grand.png"] = "rbxassetid://107634030661423",
	["sprites/house_cottage.png"] = "rbxassetid://121850938070633",
	["sprites/fence_rail.png"] = "rbxassetid://101224413256307",
	["sprites/fence_post.png"] = "rbxassetid://108806966434886",
	["sprites/cow_brown.png"] = "rbxassetid://89451722715773",
	["sprites/chicken_yellow.png"] = "rbxassetid://112671197884511",
	["sprites/chicken_red.png"] = "rbxassetid://118923848447314",
	["sprites/chest_closed.png"] = "rbxassetid://127709029106222",
}
