--!strict
-- Auto-generated by `tarmac sync --target roblox` (see tarmac.toml) —
-- do not hand-edit. This stub (empty table) is checked in so the repo
-- works before the first sync; running tarmac overwrites it with real
-- `{ [path] = "rbxassetid://..." }` entries for everything under assets/.
return {}
