--!strict
-- Auto-generated by `tarmac sync --target roblox` (see tarmac.toml) — this
-- particular batch was instead uploaded manually via create.roblox.com and
-- hand-transcribed here (Liam's machine hit a Tarmac/Roblox CSRF-handshake
-- issue that manual upload sidesteps) — same `{ [path] = "rbxassetid://..." }`
-- shape either way, so nothing else needs to change once uploads succeed
-- normally. Every image the game needs is now uploaded.
return {
	-- The character walk/idle sheets, driving the 2D sprite-character
	-- conversion (CharacterSpriteController.lua). These two are *Image*
	-- assets (uploaded via Studio's Asset Manager), NOT Decal assets like
	-- every other entry here — every other sprite below is only ever used
	-- as a Decal.Texture (MapBuilder.placeProps), which happily accepts a
	-- Decal id, but these are used as ImageLabel.Image, which does not. The
	-- first upload of these two came back as Decal ids and silently never
	-- loaded. If you ever re-upload them, use Asset Manager > Images.
	--
	-- Re-uploaded after tools/make_player_side_rows.py replaced row 2 (the
	-- pack's row 2 was a second front-facing pose, not a side profile —
	-- the actual cause of the moonwalk). The previous ids permanently
	-- serve the profile-less art, since Roblox assets are immutable.
	["sprites/player_idle.png"] = "rbxassetid://128174097168297",
	["sprites/player_walk.png"] = "rbxassetid://125467894282641",
	-- Per-cell horizontal flips of the two sheets above
	-- (tools/make_mirrored_player_sheets.py). The generated side profile
	-- faces RIGHT, so these serve walking LEFT.
	["sprites/player_idle_mirror.png"] = "rbxassetid://106497174912869",
	["sprites/player_walk_mirror.png"] = "rbxassetid://99081639846142",
	-- Drawn by tools/make_fishing_rod_sprite.py (the pack has no rod art).
	-- Used as a Decal on FishingRig's rod standee.
	["sprites/fishing_rod.png"] = "rbxassetid://122948917384062",
	-- Drawn by tools/make_water_tile.py — seamless, and animated at
	-- runtime by WaterController scrolling its offset per tile.
	-- Re-uploaded after the dash-period seam fix; the previous id
	-- (139611448879928) permanently serves the seamed art, since Roblox
	-- assets are immutable.
	["tiles/water.png"] = "rbxassetid://121025605768602",
	-- The whole fish + loot roster on one sheet (tools/make_fish_sheet.py),
	-- cropped per-species at runtime via FishSpriteSheet.lua. If catches
	-- render as a dark-blue fragment instead of a clean pixel fish, the
	-- uploaded file was a chat preview, not assets/sprites/fish_sheet.png —
	-- re-upload the real file and replace this id.
	-- Re-uploaded after the sheet builder started centring each cell's
	-- artwork; the previous id (85432915523617) serves the left-aligned
	-- version, which sat visibly off-centre in CatchShowcaseUI.
	["sprites/fish_sheet.png"] = "rbxassetid://78584010276934",
	-- The four ground tiles (tools/make_ground_tiles.py). Never uploaded
	-- before this batch — the old placeholder grass.png was a 16x16 single
	-- flat colour, so the ground had no way to look like anything but
	-- MapConfig's fallbackColor.
	["tiles/grass.png"] = "rbxassetid://92954737584427",
	["tiles/sakura_grass.png"] = "rbxassetid://100479103017033",
	["tiles/path.png"] = "rbxassetid://98093140302876",
	["tiles/tilled_soil.png"] = "rbxassetid://100134395813240",
	["sprites/player_placeholder.png"] = "rbxassetid://113485555309209",
	["sprites/petal.png"] = "rbxassetid://135838448433089",
	["sprites/kaya_placeholder.png"] = "rbxassetid://99746438596164",
	["sprites/tree_stump.png"] = "rbxassetid://72359641625412",
	["sprites/tree_small.png"] = "rbxassetid://103423679833698",
	["sprites/tree_large.png"] = "rbxassetid://108710081749902",
	["sprites/stone_round.png"] = "rbxassetid://112269019544306",
	["sprites/stone_cluster.png"] = "rbxassetid://139304812145738",
	["sprites/shrine_torii.png"] = "rbxassetid://83201818922646",
	["sprites/lantern.png"] = "rbxassetid://82367659629626",
	["sprites/house_grand.png"] = "rbxassetid://107634030661423",
	["sprites/house_cottage.png"] = "rbxassetid://121850938070633",
	["sprites/fence_rail.png"] = "rbxassetid://101224413256307",
	["sprites/fence_post.png"] = "rbxassetid://108806966434886",
	["sprites/cow_brown.png"] = "rbxassetid://89451722715773",
	["sprites/chicken_yellow.png"] = "rbxassetid://112671197884511",
	["sprites/chicken_red.png"] = "rbxassetid://118923848447314",
	["sprites/chest_closed.png"] = "rbxassetid://127709029106222",
}
