--!strict
-- Shared scoring for both rhythm-based minigames in the game: cooking
-- (RhythmGameConfig.lua charts) and fishing reel-in (procedurally
-- generated by FishingService — see GDD.md §10 for why these two systems
-- share one implementation instead of being built twice).

export type TimingWindow = {
	name: string,
	toleranceSeconds: number,
	qualityScore: number,
}

export type Note = {
	time: number,
	lane: number,
}

export type Hit = {
	noteIndex: number,
	offsetSeconds: number, -- signed delta: actualPressTime - note.time
}

local RhythmScoring = {}

-- assistMode widens every window's tolerance by this multiplier
-- (GDD.md §3 "Assist Mode" accessibility option).
local ASSIST_MODE_MULTIPLIER = 1.6

function RhythmScoring.classify(offsetSeconds: number, windows: { TimingWindow }, assistMode: boolean?): TimingWindow
	local absOffset = math.abs(offsetSeconds)
	local multiplier = assistMode and ASSIST_MODE_MULTIPLIER or 1
	for _, window in windows do
		if absOffset <= window.toleranceSeconds * multiplier then
			return window
		end
	end
	return windows[#windows]
end

-- Returns a quality score from 0-100. Missing notes count as a Miss
-- (0 quality) rather than being excluded, so spamming inputs can't
-- inflate the average.
function RhythmScoring.score(notes: { Note }, hits: { Hit }, windows: { TimingWindow }, assistMode: boolean?): number
	if #notes == 0 then
		return 0
	end

	local hitByNote: { [number]: Hit } = {}
	for _, hit in hits do
		-- if a note somehow gets hit twice, keep the more accurate hit
		local existing = hitByNote[hit.noteIndex]
		if not existing or math.abs(hit.offsetSeconds) < math.abs(existing.offsetSeconds) then
			hitByNote[hit.noteIndex] = hit
		end
	end

	local total = 0
	for i = 1, #notes do
		local hit = hitByNote[i]
		if hit then
			local window = RhythmScoring.classify(hit.offsetSeconds, windows, assistMode)
			total += window.qualityScore
		end
	end

	return total / #notes
end

return RhythmScoring
