--!strict
-- Shared scoring for both rhythm-based minigames in the game: cooking
-- (RhythmGameConfig.lua charts) and fishing reel-in (procedurally
-- generated by FishingService — see GDD.md §10 for why these two systems
-- share one implementation instead of being built twice).
--
-- Includes a combo bonus (consecutive top-tier hits push quality above
-- the raw average, capped) so nailing a streak actually feels like
-- something instead of just averaging out — the anime-rhythm-game
-- "cooler" pass, see GDD.md §11.

export type TimingWindow = {
	name: string,
	toleranceSeconds: number,
	qualityScore: number,
}

export type Note = {
	time: number,
	lane: number,
}

export type Hit = {
	noteIndex: number,
	offsetSeconds: number, -- signed delta: actualPressTime - note.time
}

export type EvaluationResult = {
	quality: number, -- 0-100, includes combo bonus
	maxCombo: number, -- longest run of consecutive top-tier ("Perfect") hits
	topWindowName: string, -- name of the window combos are counted against
}

local RhythmScoring = {}

-- assistMode widens every window's tolerance by this multiplier
-- (GDD.md §3 "Assist Mode" accessibility option).
local ASSIST_MODE_MULTIPLIER = 1.6

-- Combo bonus: +2 quality per consecutive top-tier hit, capped at a
-- 5-streak (+10 quality) — enough to feel rewarding without trivializing
-- the base scoring.
local COMBO_BONUS_PER_HIT = 2
local COMBO_BONUS_CAP_STREAK = 5

function RhythmScoring.classify(offsetSeconds: number, windows: { TimingWindow }, assistMode: boolean?): TimingWindow
	local absOffset = math.abs(offsetSeconds)
	local multiplier = assistMode and ASSIST_MODE_MULTIPLIER or 1
	for _, window in windows do
		if absOffset <= window.toleranceSeconds * multiplier then
			return window
		end
	end
	return windows[#windows]
end

local function findTopWindow(windows: { TimingWindow }): TimingWindow
	local top = windows[1]
	for _, window in windows do
		if window.qualityScore > top.qualityScore then
			top = window
		end
	end
	return top
end

-- Missing notes count as a Miss (0 quality, breaks combo) rather than
-- being excluded, so spamming inputs can't inflate the average.
function RhythmScoring.evaluate(notes: { Note }, hits: { Hit }, windows: { TimingWindow }, assistMode: boolean?): EvaluationResult
	local topWindow = findTopWindow(windows)

	if #notes == 0 then
		return { quality = 0, maxCombo = 0, topWindowName = topWindow.name }
	end

	local hitByNote: { [number]: Hit } = {}
	for _, hit in hits do
		-- if a note somehow gets hit twice, keep the more accurate hit
		local existing = hitByNote[hit.noteIndex]
		if not existing or math.abs(hit.offsetSeconds) < math.abs(existing.offsetSeconds) then
			hitByNote[hit.noteIndex] = hit
		end
	end

	local total = 0
	local combo = 0
	local maxCombo = 0

	for i = 1, #notes do
		local hit = hitByNote[i]
		if hit then
			local window = RhythmScoring.classify(hit.offsetSeconds, windows, assistMode)
			total += window.qualityScore
			if window.name == topWindow.name then
				combo += 1
				maxCombo = math.max(maxCombo, combo)
			else
				combo = 0
			end
		else
			combo = 0
		end
	end

	local baseQuality = total / #notes
	local comboBonus = math.min(maxCombo, COMBO_BONUS_CAP_STREAK) * COMBO_BONUS_PER_HIT
	local quality = math.min(100, baseQuality + comboBonus)

	return { quality = quality, maxCombo = maxCombo, topWindowName = topWindow.name }
end

return RhythmScoring
